/**
 * Where the built-in curriculum pictures live.
 *
 * Files are generated by `scripts/generate-artwork.mjs` into
 * `public/curriculum/examples/` and named after the word, so a real
 * illustration can replace the placeholder simply by overwriting the file:
 *
 *   public/curriculum/examples/apple.svg
 *
 * Nothing else in the app needs to change when that happens.
 */

/** Must match `slugify()` in scripts/generate-artwork.mjs. */
export function artworkSlug(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function picturePath(word: string): string {
  return `/curriculum/examples/${artworkSlug(word)}.svg`;
}
